Hotel_El_Dorado_Admin/Hotel_El_Dorado_Admin/Controllers/AdministradorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Hotel_El_Dorado_Admin.Models;
using Hotel_El_Dorado_Admin.Business;

namespace Hotel_El_Dorado_Admin.Controllers
{

    public class AdministradorController : Controller
    {
        public IConfiguration Configuration { get;}
        private readonly IHostingEnvironment _webhost;
        public AdministradorController(IConfiguration configuration, IHostingEnvironment webhost)
        {
            Configuration = configuration;
            _webhost = webhost;
        }
        public bool getLogin()
        {
            if (Cache.Instance.isLogged)
            {
                int valor = (int)HttpContext.Session.GetInt32("variableInt");
                string nombre = HttpContext.Session.GetString("nombreAdmin");
                ViewBag.nombre = nombre;
                ViewBag.Session = valor;

                return true;
            }
            return false;
        }
        public IActionResult ConsultarDisponibilidad() 
        {
            getLogin();
            return View();
        }

        public IActionResult Login()
        {
            HttpContext.Session.SetString("variableSession", "valor en session");
            HttpContext.Session.SetInt32("variableInt", 0);
            return View();
        }

        [HttpPost]
        public IActionResult Login(AdministradorModel model)
        {
            /*
            * Comprueba si ya ha iniciado sesión
            */
            if(!Cache.Instance.isLogged)
            {
                Cache.Instance.isLogged = true;

                AdministradorBusiness administradorBusiness = new AdministradorBusiness(Configuration);
                List<AdministradorModel> lista = administradorBusiness.login(model);
                if (lista.Count > 0) 
                {
                    HttpContext.Session.SetString("nombreAdmin", lista[0].nombre);
                    int valor = lista[0].id;

                    HttpContext.Session.SetInt32("variableInt", valor);
                    return RedirectToAction("Index");
                }
            }
            return View();

        }

        public IActionResult Index()
        {
            if (Cache.Instance.isLogged)
            {
                AdministradorBusiness admin = new AdministradorBusiness(Configuration);
                HotelModel hotel = new HotelModel();
                hotel = admin.ObtenerHome();
                getLogin();
                return View(hotel);
            }
            return RedirectToAction("Login");
        }

        public IActionResult logOut()
        {
            Cache.Instance.isLogged = false;
            HttpContext.Session.Clear();
            return RedirectToAction("Login");
        }

        [HttpPost]
        public IActionResult ActualizarHabitacionStandard(HabitacionModel model, string descripcion)
        {

            model.Descripcion = descripcion;
            model.Tipo_Habitacion = 1;
            model.Imagen = copiarImagen();
            if (model.Imagen != "")
            {
                HabitacionBusiness habitacionBusiness = new HabitacionBusiness(Configuration);
                
                habitacionBusiness.ActualizarHabitacionConImagen(model);
            }
            else
            {
                HabitacionBusiness habitacionBusiness = new HabitacionBusiness(Configuration);
                habitacionBusiness.ActualizarHabitacionSinImagen(model);
            }

            return RedirectToAction("verHabitacionStandard");
        }

        [HttpPost]
        public IActionResult ActualizarHabitacionJunior(HabitacionModel model, string descripcion)
        {

            model.Descripcion = descripcion;
            model.Tipo_Habitacion = 2;
            model.Imagen = copiarImagen();
            if (model.Imagen != "")
            {
                HabitacionBusiness habitacionBusiness = new HabitacionBusiness(Configuration);
                
                habitacionBusiness.ActualizarHabitacionConImagen(model);
            }
            else
            {
                HabitacionBusiness habitacionBusiness = new HabitacionBusiness(Configuration);
                habitacionBusiness.ActualizarHabitacionSinImagen(model);
            }
            

            return RedirectToAction("verHabitacionJunior");
        }

        [HttpPost]
        public IActionResult ActualizarHabitacionSuit(HabitacionModel model, string descripcion)
        {

            model.Descripcion = descripcion;
            model.Tipo_Habitacion = 3;
            model.Imagen = copiarImagen();
            if (model.Imagen != "")
            {
                HabitacionBusiness habitacionBusiness = new HabitacionBusiness(Configuration);
                
                habitacionBusiness.ActualizarHabitacionConImagen(model);
            }
            else
            {
                HabitacionBusiness habitacionBusiness = new HabitacionBusiness(Configuration);
                habitacionBusiness.ActualizarHabitacionSinImagen(model);
            }

            return RedirectToAction("verHabitacionSuit");
        }

        public IActionResult habitacionStandard()
        {
            HabitacionBusiness habitacionBusiness = new HabitacionBusiness(Configuration);
            List<HabitacionModel> listaHabitacion = new List<HabitacionModel>();
            listaHabitacion = habitacionBusiness.obtenerTipoHabitacionStandard();
            getLogin();
            ViewBag.ListaHabitacion = listaHabitacion;
            return View();
        }

        public IActionResult verHabitacionStandard()
        {
            HabitacionBusiness habitacionBusiness = new HabitacionBusiness(Configuration);
            List<HabitacionModel> listaHabitacion = new List<HabitacionModel>();
            listaHabitacion = habitacionBusiness.obtenerStandard();
            getLogin();
            ViewBag.ListaHabitacion = listaHabitacion;
            return View();
        }
        public IActionResult habitacionJunior()
        {
            HabitacionBusiness habitacionBusiness = new HabitacionBusiness(Configuration);
            List<HabitacionModel> listaHabitacion = new List<HabitacionModel>();
            listaHabitacion = habitacionBusiness.obtenerTipoHabitacionJunnior();
            getLogin();
            ViewBag.ListaHabitacion = listaHabitacion;
            return View();
        }

        public IActionResult verHabitacionJunior()
        {
            HabitacionBusiness habitacionBusiness = new HabitacionBusiness(Configuration);
            List<HabitacionModel> listaHabitacion = new List<HabitacionModel>();
            listaHabitacion = habitacionBusiness.obtenerJunnior();
            getLogin();
            ViewBag.ListaHabitacion = listaHabitacion;
            return View();
        }

        public IActionResult habitacionSuit()
        {
            HabitacionBusiness habitacionBusiness = new HabitacionBusiness(Configuration);
            List<HabitacionModel> listaHabitacion = new List<HabitacionModel>();
            listaHabitacion = habitacionBusiness.obtenerTipoHabitacionSuit();
            getLogin();
            ViewBag.ListaHabitacion = listaHabitacion;
            return View();
        }

        public IActionResult verHabitacionSuit()
        {
            HabitacionBusiness habitacionBusiness = new HabitacionBusiness(Configuration);
            List<HabitacionModel> listaHabitacion = new List<HabitacionModel>();
            listaHabitacion = habitacionBusiness.obtenerSuit();
            getLogin();
            ViewBag.ListaHabitacion = listaHabitacion;
            return View();
        }

        public IActionResult EstadoActualHabitacion()
        {
            AdministradorBusiness administradorBusiness = new AdministradorBusiness(Configuration);

            List<HabitacionModel> listaHabitaciones = new List<HabitacionModel>();
            listaHabitaciones = administradorBusiness.ObtenerHabitaciones();

            List<ReservacionModel> listaReservaciones = new List<ReservacionModel>();
            listaReservaciones = administradorBusiness.ObtenerReservaciones();

            List<EstadoDiarioModel> listaEstadoDiario = new List<EstadoDiarioModel>();

            bool ocupado = false;

            for (int i = 0; i < listaHabitaciones.Count(); i++)
            {

                for (int j = 0; j < listaReservaciones.Count(); j++)
                {
                    if (listaHabitaciones[i].ID_Habitacion == listaReservaciones[j].Habitacion.ID_Habitacion)
                    {
                        ocupado = true;
                        break;
                    }
                }

                if (ocupado)
                {
                    for (int j = 0; j < listaReservaciones.Count(); j++)
                    {
                        if (listaHabitaciones[i].ID_Habitacion == listaReservaciones[j].Habitacion.ID_Habitacion)
                        {
                            EstadoDiarioModel estadoDiario = new EstadoDiarioModel();
                            estadoDiario.Estado = "Ocupado";
                            estadoDiario.Fecha_Entrada = listaReservaciones[j].Fecha_Entrada;
                            estadoDiario.Fecha_Reservacion = listaReservaciones[j].Fecha_Reservacion;
                            estadoDiario.Fecha_Salida = listaReservaciones[j].Fecha_Salida;
                            estadoDiario.ID_Reservacion = listaReservaciones[j].ID_Reservacion.ToString();
                            estadoDiario.Habitacion.Numero_Habitacion = listaHabitaciones[i].Numero_Habitacion;

Hotel_El_Dorado_Admin/Hotel_El_Dorado_Admin/Controllers/OfertaController.cs
using Hotel_El_Dorado_Admin.Models;
using Hotel_El_Dorado_Admin.Business;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Http;
using System.Net.Http.Headers;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace Hotel_El_Dorado_Admin.Controllers
{
    public class OfertaController : Controller
    {
        public IConfiguration Configuration { get; }
        private static string Imagen = "";
        private readonly IWebHostEnvironment _iweb;
        private readonly IHostingEnvironment _webhost;

        public OfertaController(IConfiguration configuration, IHostingEnvironment webhost)
        {
            Configuration = configuration;
            _webhost = webhost;
        }

        public string copiarImagen()
        {
            var newFileName = string.Empty;
            var fileName = "";
            if (HttpContext.Request.Form.Files != null)
            {
                fileName = string.Empty;
                string PathDB = string.Empty;

                var files = HttpContext.Request.Form.Files;

                foreach (var file in files)
                {
                    if (file.Length > 0)
                    {
                        //Getting FileName
                        fileName = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');

                        //Assigning Unique Filename (Guid)
                        var myUniqueFileName = Path.GetFileNameWithoutExtension(fileName);

                        //Getting file Extension
                        var FileExtension = Path.GetExtension(fileName);

                        // concating  FileName + FileExtension
                        newFileName = myUniqueFileName + FileExtension;

                        // Combines two strings into a path.
                        fileName = Path.Combine(_webhost.WebRootPath, "img") + $@"\{newFileName}";

                        // if you want to store path of folder in database
                        PathDB = "img/" + newFileName;

                        using (FileStream fs = System.IO.File.Create(fileName))
                        {
                            file.CopyTo(fs);
                            fs.Flush();
                        }
                    }
                }
            }

            return newFileName;
        }
        public bool getLogin()
        {
            if (Cache.Instance.isLogged)
            {
                int valor = (int)HttpContext.Session.GetInt32("variableInt");
                string nombre = HttpContext.Session.GetString("nombreAdmin");
                ViewBag.nombre = nombre;
                ViewBag.Session = valor;

                return true;
            }
            return false;
        }
        public IActionResult Index()
        {
            getLogin();
            return View();
        }


        public IActionResult InsertarOferta()
        {
            getLogin();
            return View();
        }


        [HttpPost]
        public IActionResult guardarOferta(OfertaModel temp)
        {
            AdministradorBusiness TemBussi = new AdministradorBusiness(Configuration);
            Console.WriteLine(temp.Imagen);
            temp.Imagen = copiarImagen();
            TemBussi.guardarOferta(temp);
            getLogin();
            return RedirectToAction("VisualizarOferta");
        }


        public IActionResult VisualizarOferta()
        {
            AdministradorBusiness TemBussi = new AdministradorBusiness(Configuration);
            List<OfertaModel> var = new List<OfertaModel>();
            var = TemBussi.ObtenerOfertas();
            getLogin();
            return View(var);
        }

        public IActionResult EliminarOferta(OfertaModel temp)
        {
            AdministradorBusiness TemBussi = new AdministradorBusiness(Configuration);
            TemBussi.eliminarOferta(temp);
            getLogin();
            return RedirectToAction("VisualizarOferta");
        }

      
        public IActionResult EditarOferta(OfertaModel temp)
        {
            Console.WriteLine("fecha i " + temp.Fecha_Inicio);
            Console.WriteLine("fecha f " + temp.Fecha_Fin);
            ViewData["data"] = temp;
            getLogin();
            return View();
        }

        public IActionResult ModificarOferta(OfertaModel temp)
        {
            AdministradorBusiness TemBussi = new AdministradorBusiness(Configuration);
            temp.Imagen = copiarImagen();
            TemBussi.editarOferta(temp);
            getLogin();
            return RedirectToAction("VisualizarOferta");
        }


    }
}

Hotel_El_Dorado_Admin/Hotel_El_Dorado_Admin/Controllers/TemporadaController.cs
using Hotel_El_Dorado_Admin.Business;
using Hotel_El_Dorado_Admin.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hotel_El_Dorado_Admin.Controllers
{
    public class TemporadaController : Controller
    {
        public IConfiguration Configuration { get; }

        public TemporadaController(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public bool getLogin()
        {
            if (Cache.Instance.isLogged)
            {
                int valor = (int)HttpContext.Session.GetInt32("variableInt");
                string nombre = HttpContext.Session.GetString("nombreAdmin");
                ViewBag.nombre = nombre;
                ViewBag.Session = valor;

                return true;
            }
            return false;
        }
        public IActionResult InsertarTemporada()
        {
            getLogin();
            return View();
        }

        [HttpPost]
        public IActionResult guardarTemporada(TemporadaModel temp)
        {
            AdministradorBusiness TemBussi = new AdministradorBusiness(Configuration);
            TemBussi.guardarTemporada(temp);
            getLogin();
            return RedirectToAction("VisualizarTemporada");
        }


        public IActionResult EliminarTemporada (TemporadaModel temp)
        {
            AdministradorBusiness TemBussi = new AdministradorBusiness(Configuration);
            TemBussi.eliminarTemporada(temp);
            getLogin();
            return RedirectToAction("VisualizarTemporada");
        }

        public IActionResult EditarTemporada(TemporadaModel temp)
        {
            ViewData["item"] = temp;
            getLogin();
            return View();
        }

        public IActionResult ModificarTemporada(TemporadaModel temp)
        {
            AdministradorBusiness TemBussi = new AdministradorBusiness(Configuration);
            TemBussi.editarTemporada(temp);
            getLogin();
            return RedirectToAction("VisualizarTemporada");
        }

        public IActionResult VisualizarTemporada()
        {
            AdministradorBusiness adminBus = new AdministradorBusiness(Configuration);
            List<TemporadaModel> temp = new List<TemporadaModel>();
            temp = adminBus.ObtenerTemporada();
            getLogin();
            return View(temp);
        }


    }
}

Hotel_El_Dorado_Admin/Hotel_El_Dorado_Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hotel_El_Dorado_Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script type="text/javascript" src="~/js/site.js"></script>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Estilo.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <script type="text/javascript" src="~/lib/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="~/js/html2pdf.bundle.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="col-6 col-sm-6 col-md-8 col-lg-8 col-xl-8 logo">
                <a asp-controller="Administrador" asp-action="Index" class="logoImagen"><img class="logoImagen" src="~/img/logos.png"></a>
                <h2 id="h2">Hotel El Dorado</h2>
                <span id="h2">Modulo Administrativo</span>
            </div>

            <div class="navbar-collapse cerrar" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                </ul>
                <h4 id="h2" class="welcome"> Bienvenido @ViewBag.nombre</h4> 
                <a asp-controller="Administrador" asp-action="logOut" class="btn btn-dark btnCerrarSeesion">Cerrar sesión</a>
            </div>
        </nav>


    </header>
     <div class="row contenido">
        <div class="col-md-2 menuContenido">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse" id="collapsibleNavbar">
                        <div class="list-group  sidebar">
                            <a asp-controller="Administrador" asp-action="Index" class="text-dark list-group-item list-group-item-action">Home</a>
                            <a asp-controller="Administrador" class="text-dark list-group-item list-group-item-action" data-toggle="collapse" data-target="#modificarPage">Modificar Páginas</a>
                           <div class="collapse" id="modificarPage">
                                <a asp-controller="Administrador" asp-action="EditarHome" class="text-dark list-group-item list-group-item-action">Home</a>
                                 <a asp-controller="Administrador" asp-action="EditarSobreNosotros" class="text-dark list-group-item list-group-item-action">Sobre Nosotros</a>
                                <a asp-controller="Administrador" asp-action="EditarFacilidad" class="text-dark list-group-item list-group-item-action">Facilidades</a>
                                <a asp-controller="Administrador" asp-action="EditarComoLlegar" class="text-dark list-group-item list-group-item-action">Como Llegar</a>
                           </div>                          
                            <a asp-controller="Administrador" asp-action="verListadoReservacion" class="text-dark list-group-item list-group-item-action">Listado de reservaciones</a>
                            <a asp-controller="Administrador" class="text-dark list-group-item list-group-item-action" data-toggle="collapse" data-target="#habitaciones">Administrar habitaciones</a>    
                            <div class="collapse" id="habitaciones">
                                <a asp-controller="Administrador" asp-action="habitacionStandard" class="text-dark list-group-item list-group-item-action">Standard</a>
                                <a asp-controller="Administrador" asp-action="habitacionJunior" class="text-dark list-group-item list-group-item-action">Junior</a>
                                <a asp-controller="Administrador" asp-action="habitacionSuit" class="text-dark list-group-item list-group-item-action">Suit</a>
                           </div>
                            <a asp-controller="Administrador" asp-action="EstadoActualHabitacion" class="text-dark list-group-item list-group-item-action">Ver estado del hotel hoy</a>
                            <a asp-controller="Administrador" asp-action="ConsultarDisponibilidad" class="text-dark list-group-item list-group-item-action">Consultar disponibilidad de habitaciones</a>

                            <a asp-controller="Administrador" class="text-dark list-group-item list-group-item-action" data-toggle="collapse" data-target="#administrarTemporada">Administrar Temporada</a>  
                            <div class="collapse" id="administrarTemporada">
                                <a asp-controller="Temporada" asp-action="InsertarTemporada" class="text-dark list-group-item list-group-item-action">Insertar temporada</a>
                                <a asp-controller="Temporada" asp-action="VisualizarTemporada" class="text-dark list-group-item list-group-item-action">Administrar Temporada</a>
                            </div>
                            <a asp-controller="Administrador" class="text-dark list-group-item list-group-item-action" data-toggle="collapse" data-target="#administrarOferta">Administrar Oferta</a>
                            <div class="collapse" id="administrarOferta">
                                <a asp-controller="Oferta" asp-action="InsertarOferta" class="text-dark list-group-item list-group-item-action">Insertar Oferta</a>
                                <a asp-controller="Oferta" asp-action="VisualizarOferta" class="text-dark list-group-item list-group-item-action">Administrar Oferta</a>
                            </div>
                            <a asp-controller="Administrador" class="text-dark list-group-item list-group-item-action" data-toggle="collapse" data-target="#administrarPublicidad">Publicidad</a>
                            <div class="collapse" id="administrarPublicidad">
                                <a asp-controller="Administrador" asp-action="InsertarPublicidad" class="text-dark list-group-item list-group-item-action">Insertar Publicidad</a>
                                <a asp-controller="Administrador" asp-action="verPublicidad" class="text-dark list-group-item list-group-item-action">Publicidades</a>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
        <div class="col-md-8">
            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="containerFooter">
           Copyright&copy;Hotel El Dorado 2022
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Hotel_El_Dorado_Admin/Hotel_El_Dorado_Admin/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hotel_El_Dorado_Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script type="text/javascript" src="~/js/functions.js"></script>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Estilo.css" />
    <script type="text/javascript" src="~/lib/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <header>
       <div class="row logoContent">
            <div class="col-6 logo">
                <a asp-controller="Administrador" asp-action="Login" class="logoImagen"><img class="logoImagen" src="~/img/logos.png"></a>
                <h2 id="h2">Hotel El Dorado</h2>
                <span id="h2">Modulo Administrativo</span>
            </div>
       </div>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="containerFooter">
           Copyright&copy;Hotel El Dorado 2022
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>